// Generated by lgx.guru. AI-authored tests are appended below the
// smoke test. The build pipeline runs these after the main module
// build; failures feed back to the AI for retry.
#include <logos_test.h>
#include "../src/calculator_impl.h"

// Smoke test — proves the impl class can be constructed and destroyed
// without crashing. Always passes for a well-formed module.
LOGOS_TEST(calculator_constructs) {
    CalculatorImpl impl;
    (void)impl;
    LOGOS_ASSERT_TRUE(true);
}

// Test the calculate method with a sample expression.
LOGOS_TEST(test_calculate) {
    CalculatorImpl impl;
    LOGOS_ASSERT_EQ(impl.calculate("2.0"), "2.00");
}

// Test the lastCalculation method returns correct result.
LOGOS_TEST(test_lastCalculation) {
    CalculatorImpl impl;
    impl.calculate("10.0");
    LOGOS_ASSERT_EQ(impl.lastCalculation(), "10.00");
}
