// Generated by lgx.guru. AI-authored tests are appended below the
// smoke test. The build pipeline runs these after the main module
// build; failures feed back to the AI for retry.
#include <logos_test.h>
#include "../src/simple_calculator_impl.h"

// Smoke test — proves the impl class can be constructed and destroyed
// without crashing. Always passes for a well-formed module.
LOGOS_TEST(simple_calculator_constructs) {
    SimpleCalculatorImpl impl;
    (void)impl;
    LOGOS_ASSERT_TRUE(true);
}

// Test addition method.
LOGOS_TEST(addition_test) {
    SimpleCalculatorImpl impl;
    LOGOS_ASSERT_EQ(impl.add(3, 5), 8);
}

// Test subtraction method.
LOGOS_TEST(subtraction_test) {
    SimpleCalculatorImpl impl;
    LOGOS_ASSERT_EQ(impl.subtract(10, 4), 6);
}

// Test multiplication method.
LOGOS_TEST(multiplication_test) {
    SimpleCalculatorImpl impl;
    LOGOS_ASSERT_EQ(impl.multiply(6, 7), 42);
}

// Test division method.
LOGOS_TEST(division_test) {
    SimpleCalculatorImpl impl;
    LOGOS_ASSERT_EQ(impl.divide(8, 2), 4); LOGOS_ASSERT_EQ(impl.divide(5, 0), 0);
}
